# Task 1: 

**1. Write a function to compute 5/0 and use try/except to catch the exceptions.** 

In [1]:
def divide_by_zero():
  try:
    return 5 / 0
  except Exception as e:
    return("Exception Occured : "+str(e))

print(divide_by_zero())

Exception Occured : division by zero


**2.Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].**

**Hint:** Subject,Verb and Object should be declared in the program as shown below.
``` 
subjects=["Americans ","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"] 
 ```
**Output should come as below:**
 ```
Americans  play Baseball. 
Americans  play Cricket. 
Americans  watch Baseball. 
Americans  watch Cricket. 
Indians play Baseball. 
Indians play Cricket.
Indians watch Baseball. 
Indians watch Cricket. 
```

In [2]:
subjects = ["Americans","Indians"]
verbs = ["play","watch"]
objects = ["baseball","cricket"]

for i in subjects:
    
    for j in verbs:
               
        for k in objects:
            print(i, j, k, end = ".")
            print()



Americans play baseball.
Americans play cricket.
Americans watch baseball.
Americans watch cricket.
Indians play baseball.
Indians play cricket.
Indians watch baseball.
Indians watch cricket.


# Task 2:  

**1. Write a function so that the columns of the output matrix are powers of the input vector.**

**The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.** 

**HINT:** Such a matrix with a geometric progression in each row is named for Alexandre               Theophile Vandermonde

In [3]:
import numpy as np
x = np.array([1,2,3,4])
N = 4
np.vander(x,N, increasing = False)
print(np.column_stack([x**(N-i-1) for i in range(N)]))


[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
